### ISSUE TITLE
Comentario

### ISSUE THREAD

**Issue by AlvaroMartinFernandez** [4GeeksAcademy/pt67-instagramfeed-JavierPintado#1]
Te dejo unas correcciones:

- [ ] Las imagenes deberian ser distintas almenos utiliza 3 diferentes y se tendrian que visualizar del mismo tamaño, deberias utilizar el img-fluid y el object fit cover de bootstrap. Tambien la separacion en horizontal y en vertical deberia ser la misma 
<img width="1046" alt="image" src="https://github.com/4GeeksAcademy/pt67-instagramfeed-JavierPintado/assets/91843474/fc95e6f9-dc1d-4f56-8c42-508e3e0a60d9">

- [ ] La imagen en la vista de una sola columna tiene que ocupar todo el ancho de la card 
<img width="584" alt="image" src="https://github.com/4GeeksAcademy/pt67-instagramfeed-JavierPintado/assets/91843474/ac64e80c-38c9-4f93-8b00-db448e4ff27d">

- [ ] estas utilizando div dentro de otros div y sin clases ni nadas para tener solo un hijo eso no seria correcto 
<img width="662" alt="image" src="https://github.com/4GeeksAcademy/pt67-instagramfeed-JavierPintado/assets/91843474/529206ff-2637-481c-a063-05a28dcf048b">
 elimina esos div que sobran

**Comment by AlvaroMartinFernandez** [comment]
dos correcciones, el modal tiene que ser igual que en el gif del enunciado, y por ultimo en a vista de 3 imágenes por fila, las imagenees tienen que tener la misma separacion en horizontal que en vertical

**Comment by javier5pe** [comment]
- Modal corregido.

- En la linea 122 he cambiado mt-4 por mt-1. 

- Con px-1 y py-1 he dado el mismo espacio entre todas las imágenes, supongo que deberían ocupar el total de la pagina web y no verse ese espacio en blanco por debajo, pero no se como hacerlo. ¿Me puedes ayudar con eso?

**Comment by AlvaroMartinFernandez** [comment]
Es por que el div de la linea 118 tiene que envolver y contener al de la  158 mira el componente como es y como lo tienes tu.

```html
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Home</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Profile</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false">Contact</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="disabled-tab" data-bs-toggle="tab" data-bs-target="#disabled-tab-pane" type="button" role="tab" aria-controls="disabled-tab-pane" aria-selected="false" disabled>Disabled</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">...</div>
  <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">...</div>
  <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">...</div>
  <div class="tab-pane fade" id="disabled-tab-pane" role="tabpanel" aria-labelledby="disabled-tab" tabindex="0">...</div>
</div>
``` 
ES una tontería por lo que te lo voy a marcar como aprobado pero cuidado con tener el contenido junto también esto es la ultima vez que lo paso  adjunto imagenen
<img width="926" alt="image" src="https://github.com/4GeeksAcademy/pt67-instagramfeed-JavierPintado/assets/91843474/e8d6ad83-2279-419a-a889-800bd66bd952">
